### ISSUE TITLE
separate /boot partition is not supported in update-grub

### ISSUE THREAD

**Issue by ey3ball** [AsahiLinux/asahi-scripts#3]
While trying to setup a fully encrypted rootfs (with a separate /boot partition), I ended up getting dropped to a grub rescue-shell (see attached shitty pic)

![image](https://user-images.githubusercontent.com/96346/159591196-69222aa4-7719-43fc-934f-4e1b5148e587.png)

Grub could not find normal.mod
I was able to fix it by changing the prefix variable.

Root cause is that the update-grub script hardcodes the following : 
```
set prefix=(\$root)'/boot/grub'
```

Which breaks if grub is installed on partition separate from /

**Comment by dkwo** [comment]
I was looking into the same: would it be fine to mount the "efi - uefi" partition (created by asahi installer in 'uefi only' mode) as /boot, and then install grub as `grub-install --target=arm64-efi --efi-directory=/boot --removable`, and not use the update-grub-script? Later I would also put there the kernel and initram, so that / can be encrypted. (I'm on Void linux btw).

**Comment by dkwo** [comment]
I believe also the `update-m1n1` script would need to be changed.

**Comment by dkwo** [comment]
It seems this recent commit https://github.com/AsahiLinux/asahi-scripts/commit/b48e49132e18fdcaba776cb7b59fc2cc7a8950fd
fixes the issues, so now it should be possible to mount efi partition at /boot without any issues.

**Comment by marcan** [comment]
This should be fixed in the new scripts, which we'll be releasing soon.
